// Mocks generated by Mockito 5.4.6 from annotations
// in mock_api_generator/test/domain/usecases/get_swagger_json_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mock_api_generator/domain/entities/swagger_entity.dart' as _i2;
import 'package:mock_api_generator/domain/repositories/swagger_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSwaggerEntity_0 extends _i1.SmartFake implements _i2.SwaggerEntity {
  _FakeSwaggerEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SwaggerRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSwaggerRepository extends _i1.Mock implements _i3.SwaggerRepository {
  @override
  _i4.Future<_i2.SwaggerEntity> getSwaggerLinkJsonData(String? link) =>
      (super.noSuchMethod(
            Invocation.method(#getSwaggerLinkJsonData, [link]),
            returnValue: _i4.Future<_i2.SwaggerEntity>.value(
              _FakeSwaggerEntity_0(
                this,
                Invocation.method(#getSwaggerLinkJsonData, [link]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.SwaggerEntity>.value(
              _FakeSwaggerEntity_0(
                this,
                Invocation.method(#getSwaggerLinkJsonData, [link]),
              ),
            ),
          )
          as _i4.Future<_i2.SwaggerEntity>);
}
